### PR TITLE
UI overhaul

### PR DESCRIPTION
**Pull request by goldenguy00**
i did too much but i think its mostly good

theres a lot of code style changes, specifically starting methods with capital letters. mostly done for my own sanity.

many of the backend changes were done with the intention of making the hud work better. 

its not a good idea to have the character rely on the hud so heavily. the hud should just be a display of backend data, not the data driver. if the hud fails, and it will fail given how many UI overhaul mods exist, then you really want to have your character still playable. even now, if the hud fails the character instantly explodes but its better than it was.

source: i do this for a living. let me know if theres any changes you disagree with and we can discuss

### CODE REVIEW

**Comment by goldenguy00** [comment]
a couple things left on the todo list:

- finish riskui hud
- change catalogs to not be dictionaries
   - replace with lookup tables and name-to-index maps
   - make skills and abilities have IDs assigned at runtime
   - work save system to be more tolerant to change
- remove character's reliance on hud to function
   - make data providers update hud on an event system
- do a heavy optimization rework
    - things arent terribly bad, but things can run significantly better if moved to eventlisteners and caching is implemented

**Comment by Mugiwaxar** [comment]
Hey!

Thank you so much for taking the time to make these modifications and for your pull request. I really appreciate the effort you put into this.

Over the past few days, I’ve made a lot of changes to my mod, which means I’m now facing conflicts with the updates you’ve proposed. I hope you understand that I won’t be merging these changes, as I’m aiming to keep my code as my own work. However, you’re more than welcome to keep and use your version of the code to enjoy it in-game if you’d like.

Just so you know, I’m not actively using GitHub as a collaborative tool for this project. I’ve uploaded the code here primarily so others can see it and help me troubleshoot or debug if needed. The GitHub version won’t always be up-to-date with my latest developments for that reason. Really, the main help I’m looking for from others is to test the mod and provide feedback on how it plays.

That said, I’ll definitely take a look at what you’ve done – it’s always interesting to see different approaches. Thanks again for your time and interest; it really means a lot!

**Comment by goldenguy00** [comment]
I fully expected this not to be merged, given how massive some of the changes are, but ill keep my branch available as a reference and will update with any changes you make. Feel free to take anything I've done, I'm just happy to be able to be involved at all. I'll be updating this branch occasionally for my own personal use, since the character is just awesome. It also gives me a bit more creative freedom this way, since I know our ideas are going to clash at times.

I guess the only thing that **_really_** should be changed on the main branch is swapping the input polling from FixedUpdate to Update, that worked great for the dropped inputs issue. Changing the input enums to a bitmask is just extra optimization, since that code will run much more often, but its not necessary.

**Comment by Mugiwaxar** [comment]
Thank you so much for the work you put into these changes! You're absolutely free to keep modifying the character for your personal use as much as you’d like. I really appreciate all the help and input you're providing. I'll be releasing an update soon with some fixes and a few changes of my own. As always, I’m open to any feedback you have—it's invaluable for pushing this mod forward!

**Pull request closed without merging**
